FROM node:13.12.0-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

RUN apk add --update nodejs nodejs-npm yarn

RUN node -v
RUN yarn -v

COPY package.json ./

RUN yarn install
RUN yarn add react-scripts@3.4.1 -g

COPY . ./

CMD ["npm", "start"]
